### PR TITLE
Support Scala 2.13 (+ SBT)

### PR DESCRIPTION
**Pull request by cchantep**

### CODE REVIEW

**Comment by cchantep** [comment]
Up

**Comment by cchantep** [comment]
Up

**Comment by nightscape** [comment]
@jverbus any chance of getting this merged? I'm trying to add Scala 2.13 support to SynapseML which uses isolation-forest.

**Comment by jverbus** [comment]
Thank you for the contribution, @cchantep! This library uses Gradle, not SBT, so I merged in a PR based upon your changes (sans SBT) here: https://github.com/linkedin/isolation-forest/pull/37

**Comment by jverbus** [comment]
A version with Scala 2.13 and Spark 3.2 is now available in Maven Central.

```
<dependency>
  <groupId>com.linkedin.isolation-forest</groupId>
  <artifactId>isolation-forest_3.2.0_2.13</artifactId>
  <version>3.0.1</version>
</dependency>
```

**Comment by nightscape** [comment]
Cool, thanks @jverbus !

**Comment by cchantep** [comment]
Thx.
BTW using Gradle for a Scala/Spark lib can hardly be considered as a good idea.

**Pull request closed without merging**
